import { writable } from 'svelte/store';

export const currentLang = writable('ko');

export const translations = {
    ko: {
        title: '스페이스 러너',
        start: '게임 시작',
        stage: '스테이지',
        score: '점수',
        highScore: '최고 점수',
        pause: '일시정지',
        resume: '계속하기',
        retry: '재도전',
        home: '홈으로',
        nextStage: '다음 스테이지',
        gameOver: '게임 오버',
        stageClear: '스테이지 클리어!',
        rotateDevice: '기기를 가로로 돌려주세요',
        selectLanguage: '언어 선택'
    },
    en: {
        title: 'Space Runner',
        start: 'Start Game',
        stage: 'Stage',
        score: 'Score',
        highScore: 'High Score',
        pause: 'Pause',
        resume: 'Resume',
        retry: 'Retry',
        home: 'Home',
        nextStage: 'Next Stage',
        gameOver: 'Game Over',
        stageClear: 'Stage Clear!',
        rotateDevice: 'Please rotate your device',
        selectLanguage: 'Select Language'
    },
    ja: {
        title: 'スペースランナー',
        start: 'ゲーム開始',
        stage: 'ステージ',
        score: 'スコア',
        highScore: 'ハイスコア',
        pause: '一時停止',
        resume: '続ける',
        retry: 'リトライ',
        home: 'ホーム',
        nextStage: '次のステージ',
        gameOver: 'ゲームオーバー',
        stageClear: 'ステージクリア！',
        rotateDevice: 'デバイスを横向きにしてください',
        selectLanguage: '言語選択'
    },
    de: {
        title: 'Space Runner',
        start: 'Spiel Starten',
        stage: 'Stufe',
        score: 'Punktzahl',
        highScore: 'Höchstpunktzahl',
        pause: 'Pause',
        resume: 'Fortsetzen',
        retry: 'Wiederholen',
        home: 'Startseite',
        nextStage: 'Nächste Stufe',
        gameOver: 'Spiel Vorbei',
        stageClear: 'Stufe Geschafft!',
        rotateDevice: 'Bitte Gerät drehen',
        selectLanguage: 'Sprache Wählen'
    },
    fr: {
        title: 'Space Runner',
        start: 'Commencer',
        stage: 'Niveau',
        score: 'Score',
        highScore: 'Meilleur Score',
        pause: 'Pause',
        resume: 'Reprendre',
        retry: 'Réessayer',
        home: 'Accueil',
        nextStage: 'Niveau Suivant',
        gameOver: 'Partie Terminée',
        stageClear: 'Niveau Terminé!',
        rotateDevice: 'Veuillez tourner votre appareil',
        selectLanguage: 'Choisir la Langue'
    },
    es: {
        title: 'Space Runner',
        start: 'Comenzar',
        stage: 'Nivel',
        score: 'Puntuación',
        highScore: 'Puntuación Máxima',
        pause: 'Pausa',
        resume: 'Continuar',
        retry: 'Reintentar',
        home: 'Inicio',
        nextStage: 'Siguiente Nivel',
        gameOver: 'Juego Terminado',
        stageClear: '¡Nivel Completado!',
        rotateDevice: 'Por favor, gire su dispositivo',
        selectLanguage: 'Seleccionar Idioma'
    },
    hi: {
        title: 'स्पेस रनर',
        start: 'खेल शुरू करें',
        stage: 'स्तर',
        score: 'स्कोर',
        highScore: 'उच्चतम स्कोर',
        pause: 'रोकें',
        resume: 'जारी रखें',
        retry: 'पुनः प्रयास करें',
        home: 'होम',
        nextStage: 'अगला स्तर',
        gameOver: 'खेल समाप्त',
        stageClear: 'स्तर पूरा!',
        rotateDevice: 'कृपया अपना डिवाइस घुमाएं',
        selectLanguage: 'भाषा चुनें'
    },
    vi: {
        title: 'Space Runner',
        start: 'Bắt Đầu',
        stage: 'Cấp Độ',
        score: 'Điểm Số',
        highScore: 'Điểm Cao Nhất',
        pause: 'Tạm Dừng',
        resume: 'Tiếp Tục',
        retry: 'Thử Lại',
        home: 'Trang Chủ',
        nextStage: 'Cấp Độ Tiếp',
        gameOver: 'Kết Thúc',
        stageClear: 'Hoàn Thành!',
        rotateDevice: 'Vui lòng xoay thiết bị',
        selectLanguage: 'Chọn Ngôn Ngữ'
    }
};
